#!/bin/bash
# Autonomous Supply Chain - Master Setup Script
# Run this ONCE to provision AlloyDB infrastructure and seed database
# Usage: ./setup.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "🚀 Autonomous Supply Chain - Setup"
echo "===================================="
echo ""

# ============================================================================
# Helper Functions
# ============================================================================

# Spinner for long-running operations
spinner() {
    local pid=$1
    local delay=0.1
    local spinstr='|/-\'
    while ps -p $pid > /dev/null 2>&1; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

# Load environment variables from .env file
load_env_file() {
    if [ -f "$SCRIPT_DIR/.env" ]; then
        echo "📄 Loading existing .env file..."
        set -a
        source "$SCRIPT_DIR/.env"
        set +a
        echo "✅ Environment variables loaded from .env"
        return 0
    fi
    return 1
}

# Generate .env file with all configuration
generate_env_file() {
    local project=$1
    local api_key=$2
    local db_pass=$3
    local cluster=$4
    local instance=$5
    local region=$6
    
    cat > "$SCRIPT_DIR/.env" <<EOF
# Auto-generated by setup.sh on $(date)
# Autonomous Supply Chain - Environment Configuration

# ============================================================================
# Vision Agent - Gemini API Key (REQUIRED)
# ============================================================================
GEMINI_API_KEY=$api_key

# ============================================================================
# Supplier Agent - GCP Project (REQUIRED)
# ============================================================================
GOOGLE_CLOUD_PROJECT=$project

# ============================================================================
# AlloyDB Database (REQUIRED)
# ============================================================================
DB_PASS=$db_pass

# ============================================================================
# AlloyDB Connection Details (Auto-detected)
# ============================================================================
# These are for reference - the Auth Proxy handles the connection
ALLOYDB_CLUSTER=$cluster
ALLOYDB_INSTANCE=$instance
ALLOYDB_REGION=$region
ALLOYDB_PROJECT=$project

# Database connection via Auth Proxy (localhost)
DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=postgres
DB_NAME=postgres
EOF
    
    echo ""
    echo "✅ Created .env file at: $SCRIPT_DIR/.env"
    echo "   All credentials saved for future runs"
}

# Parse AlloyDB instance URI to extract components
parse_instance_uri() {
    local uri=$1
    # Format: projects/PROJECT/locations/REGION/clusters/CLUSTER/instances/INSTANCE
    ALLOYDB_PROJECT=$(echo "$uri" | sed -n 's|projects/\([^/]*\).*|\1|p')
    ALLOYDB_REGION=$(echo "$uri" | sed -n 's|.*/locations/\([^/]*\).*|\1|p')
    ALLOYDB_CLUSTER=$(echo "$uri" | sed -n 's|.*/clusters/\([^/]*\).*|\1|p')
    ALLOYDB_INSTANCE=$(echo "$uri" | sed -n 's|.*/instances/\([^/]*\)|\1|p')
}

# Detect OS and architecture
detect_os() {
    case "$(uname -s)" in
        Linux*)     echo "linux";;
        Darwin*)    echo "darwin";;
        *)          echo "unknown";;
    esac
}

detect_arch() {
    case "$(uname -m)" in
        x86_64|amd64)   echo "amd64";;
        arm64|aarch64)  echo "arm64";;
        *)              echo "amd64";; # Default
    esac
}

# Try loading existing .env file first
load_env_file || true

# ============================================================================
# PRE-FLIGHT CHECKS - Run All Validations First
# ============================================================================

echo "🔍 Running pre-flight checks..."
echo ""

PREFLIGHT_ERRORS=0
PREFLIGHT_WARNINGS=0

# Check 1: gcloud CLI
echo -n "Checking gcloud CLI... "
if command -v gcloud &> /dev/null; then
    echo "✅"
else
    echo "❌"
    echo "   Error: gcloud CLI not found"
    echo "   Install: https://cloud.google.com/sdk/docs/install"
    PREFLIGHT_ERRORS=$((PREFLIGHT_ERRORS + 1))
fi

# Check 2: Python 3
echo -n "Checking Python 3... "
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
    echo "✅ ($PYTHON_VERSION)"
else
    echo "❌"
    echo "   Error: python3 not found"
    PREFLIGHT_ERRORS=$((PREFLIGHT_ERRORS + 1))
fi

# Check 3: pip3
echo -n "Checking pip3... "
if command -v pip3 &> /dev/null; then
    echo "✅"
else
    echo "⚠️ "
    echo "   Warning: pip3 not found, will attempt to use pip"
    PREFLIGHT_WARNINGS=$((PREFLIGHT_WARNINGS + 1))
fi

# Check 4: Git
echo -n "Checking git... "
if command -v git &> /dev/null; then
    echo "✅"
else
    echo "❌"
    echo "   Error: git not found (needed to clone AlloyDB setup tool)"
    PREFLIGHT_ERRORS=$((PREFLIGHT_ERRORS + 1))
fi

# Check 5: GCP Project
echo -n "Checking GCP project... "
PROJECT=$(gcloud config get-value project 2>/dev/null)
if [ -n "$PROJECT" ]; then
    echo "✅ ($PROJECT)"
    export GOOGLE_CLOUD_PROJECT=$PROJECT
else
    echo "❌"
    echo "   Error: No GCP project configured"
    echo "   Run: gcloud config set project YOUR_PROJECT_ID"
    PREFLIGHT_ERRORS=$((PREFLIGHT_ERRORS + 1))
fi

# Check 6: Billing (if project exists)
if [ -n "$PROJECT" ]; then
    echo -n "Checking billing... "
    BILLING_ENABLED=$(gcloud beta billing projects describe "$PROJECT" --format="value(billingEnabled)" 2>/dev/null || echo "false")
    if [ "$BILLING_ENABLED" = "True" ] || [ "$BILLING_ENABLED" = "true" ]; then
        echo "✅"
    else
        echo "⚠️ "
        echo "   Warning: Billing may not be enabled"
        echo "   Enable at: https://console.cloud.google.com/billing/linkedaccount?project=$PROJECT"
        PREFLIGHT_WARNINGS=$((PREFLIGHT_WARNINGS + 1))
    fi
fi

# Check 7: Required APIs
echo ""
echo "Checking required APIs..."
REQUIRED_APIS=("aiplatform.googleapis.com" "alloydb.googleapis.com" "compute.googleapis.com" "servicenetworking.googleapis.com")
MISSING_APIS=()

for api in "${REQUIRED_APIS[@]}"; do
    echo -n "  - $api... "
    if gcloud services list --enabled --filter="name:$api" --format="value(name)" 2>/dev/null | grep -q "$api"; then
        echo "✅"
    else
        echo "❌"
        MISSING_APIS+=("$api")
    fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ $PREFLIGHT_ERRORS -gt 0 ]; then
    echo "❌ Pre-flight check failed: $PREFLIGHT_ERRORS error(s)"
    echo "   Please fix the errors above and re-run setup"
    exit 1
elif [ $PREFLIGHT_WARNINGS -gt 0 ] || [ ${#MISSING_APIS[@]} -gt 0 ]; then
    echo "⚠️  Pre-flight check completed with warnings"
    if [ ${#MISSING_APIS[@]} -gt 0 ]; then
        echo ""
        echo "Missing APIs: ${MISSING_APIS[@]}"
        echo ""
        read -p "Enable missing APIs automatically? (y/N): " -n 1 -r
        echo ""
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            echo "Enabling APIs..."
            for api in "${MISSING_APIS[@]}"; do
                echo "  Enabling $api..."
                gcloud services enable "$api" --quiet
            done
            echo "✅ All APIs enabled"
        else
            echo "⚠️  Continuing without enabling APIs (may fail later)"
        fi
    fi
else
    echo "✅ All pre-flight checks passed!"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ============================================================================
# Step 1: Gemini API Key Setup & Validation
# ============================================================================
echo "🔑 Step 1/5: Setting up Gemini API Key..."
echo ""

if [ -z "$GEMINI_API_KEY" ]; then
    echo "For Vision Agent (Gemini 3 Flash with Code Execution):"
    echo "  1. Visit: https://aistudio.google.com/apikey"
    echo "  2. Click 'Create API Key'"
    echo "  3. Paste below"
    echo ""
    read -p "Enter your Gemini API key (or press Enter to skip): " API_KEY_INPUT
    if [ -n "$API_KEY_INPUT" ]; then
        export GEMINI_API_KEY=$API_KEY_INPUT
        echo "✅ API key configured"
    else
        echo "⚠️  Skipping API key - Vision Agent will not work"
    fi
else
    echo "✅ Gemini API key found (loaded from .env or environment)"
fi

# Validate API key if provided
if [ -n "$GEMINI_API_KEY" ]; then
    echo ""
    echo -n "Validating Gemini API key... "
    # Simple validation: check if it's a reasonable format
    if [[ ${#GEMINI_API_KEY} -lt 20 ]]; then
        echo "❌"
        echo "   Error: API key seems too short (expected 30+ characters)"
        echo "   Please check your key and try again"
        exit 1
    else
        echo "✅ (format valid)"
    fi
fi

echo ""

# ============================================================================
# Step 2: Python Dependencies
# ============================================================================
echo "📦 Step 2/5: Installing Python dependencies..."
echo ""

# Install database dependencies upfront
echo "Installing database libraries (psycopg2-binary, pgvector)..."
if command -v pip3 &> /dev/null; then
    pip3 install -q psycopg2-binary pgvector python-dotenv 2>&1 | tail -1
else
    pip install -q psycopg2-binary pgvector python-dotenv 2>&1 | tail -1
fi
echo "✅ Python dependencies installed"
echo ""

# ============================================================================
# Step 3: Clone Infrastructure Tool
# ============================================================================
echo "🏗️  Step 3/5: Setting up AlloyDB infrastructure..."
echo ""

if [ -d "$SCRIPT_DIR/easy-alloydb-setup" ]; then
    echo "✅ Infrastructure tool already cloned"
else
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "📦 AlloyDB Infrastructure Setup Tool"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "We need to provision AlloyDB (VPC, Cluster, Instance)."
    echo ""
    echo "What we'll do:"
    echo "  • Clone a lightweight setup tool (easy-alloydb-setup)"
    echo "  • Source: https://github.com/AbiramiSukumaran/easy-alloydb-setup"
    echo "  • Purpose: Provides a web UI to configure and deploy AlloyDB"
    echo "  • Size: ~2 MB"
    echo ""
    echo "Why this tool?"
    echo "  • Manual AlloyDB setup takes 30+ steps and 45 minutes"
    echo "  • This tool automates VPC creation, peering, and cluster provisioning"
    echo "  • Provides a visual interface to track deployment progress"
    echo "  • Auto-configures network settings and security"
    echo ""
    echo "What gets cloned to: ./easy-alloydb-setup/"
    echo ""
    read -p "Clone the AlloyDB setup tool? (Y/n): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo "❌ Cannot proceed without the infrastructure tool"
        echo "   You can manually provision AlloyDB and update .env"
        exit 1
    fi
    echo ""
    echo "📥 Cloning AlloyDB setup tool..."
    git clone https://github.com/AbiramiSukumaran/easy-alloydb-setup.git "$SCRIPT_DIR/easy-alloydb-setup" --quiet
    echo "✅ Cloned successfully to ./easy-alloydb-setup/"
fi

echo ""
echo "🌐 Starting infrastructure setup UI..."
echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  IMPORTANT: Setup Instructions                      │"
echo "├──────────────────────────────────────────────────────┤"
echo "│  1. Access via Web Preview on port 8080             │"
echo "│  2. Enter your Project ID: $PROJECT"
echo "│  3. Select Region (e.g., us-central1)               │"
echo "│  4. Set Database Password & SAVE IT!                │"
echo "│  5. Click 'Start Deployment' (~15 minutes)          │"
echo "│  6. When complete, click 'Reveal Private IP & Copy' │"
echo "│  7. Press Ctrl+C here when you see the details      │"
echo "│                                                      │"
echo "│  ✅ This script will AUTO-DETECT:                   │"
echo "│     - Cluster name, Instance, Region, Project       │"
echo "│  ⚠️  You only need to REMEMBER the password!        │"
echo "└──────────────────────────────────────────────────────┘"
echo ""
read -p "Press Enter to launch the setup UI..."

cd "$SCRIPT_DIR/easy-alloydb-setup"
sh run.sh
cd "$SCRIPT_DIR"

echo ""
echo "✅ Infrastructure provisioning complete!"
echo ""

# ============================================================================
# Step 4: Database Connection Setup
# ============================================================================
echo "📡 Step 4/5: Preparing database connection..."
echo ""

# First, detect AlloyDB instance(s)
echo "🔍 Detecting AlloyDB instance..."
INSTANCES=$(gcloud alloydb instances list --format="value(name)" 2>/dev/null)

if [ -z "$INSTANCES" ]; then
    # Try fallback from .env file variables
    if [ -n "$ALLOYDB_PROJECT" ] && [ -n "$ALLOYDB_REGION" ] && [ -n "$ALLOYDB_CLUSTER" ] && [ -n "$ALLOYDB_INSTANCE" ]; then
        INSTANCE_URI="projects/$ALLOYDB_PROJECT/locations/$ALLOYDB_REGION/clusters/$ALLOYDB_CLUSTER/instances/$ALLOYDB_INSTANCE"
        echo "✅ Using instance from .env: ${ALLOYDB_CLUSTER}/${ALLOYDB_INSTANCE}"
    else
        echo "❌ ERROR: No AlloyDB instance found"
        echo ""
        echo "Troubleshooting:"
        echo "  1. Verify deployment completed successfully in the UI"
        echo "  2. Check your GCP project: gcloud config get-value project"
        echo "  3. List all instances: gcloud alloydb instances list"
        echo "  4. If instance exists, manually add to .env file:"
        echo "     ALLOYDB_CLUSTER=your-cluster-name"
        echo "     ALLOYDB_INSTANCE=your-instance-name"
        echo "     ALLOYDB_REGION=your-region"
        echo ""
        exit 1
    fi
else
    # Count instances
    INSTANCE_COUNT=$(echo "$INSTANCES" | wc -l | tr -d ' ')
    
    if [ "$INSTANCE_COUNT" -eq 1 ]; then
        # Only one instance, use it automatically
        INSTANCE_URI="$INSTANCES"
        parse_instance_uri "$INSTANCE_URI"
        echo "✅ Found instance: ${ALLOYDB_CLUSTER}/${ALLOYDB_INSTANCE} in ${ALLOYDB_REGION}"
    else
        # Multiple instances, let user choose
        echo "✅ Found $INSTANCE_COUNT AlloyDB instances:"
        echo ""
        
        # Create array of instances
        i=1
        declare -a INSTANCE_ARRAY
        while IFS= read -r instance; do
            parse_instance_uri "$instance"
            echo "  $i) ${ALLOYDB_CLUSTER}/${ALLOYDB_INSTANCE} (${ALLOYDB_REGION})"
            INSTANCE_ARRAY[$i]="$instance"
            i=$((i + 1))
        done <<< "$INSTANCES"
        
        echo ""
        read -p "Select instance number (1-$INSTANCE_COUNT): " CHOICE
        
        if [ "$CHOICE" -ge 1 ] && [ "$CHOICE" -le "$INSTANCE_COUNT" ]; then
            INSTANCE_URI="${INSTANCE_ARRAY[$CHOICE]}"
            parse_instance_uri "$INSTANCE_URI"
            echo "✅ Selected: ${ALLOYDB_CLUSTER}/${ALLOYDB_INSTANCE} in ${ALLOYDB_REGION}"
        else
            echo "❌ Invalid selection"
            exit 1
        fi
    fi
fi

# Get database password
if [ -z "$DB_PASS" ]; then
    echo ""
    echo "⚠️  Database password not found"
    echo ""
    read -s -p "Enter your AlloyDB password from the setup UI: " DB_PASS
    echo ""
    export DB_PASS
fi

echo ""
echo "✅ Database password configured"

# Generate .env file with all collected information
if [ -n "$GEMINI_API_KEY" ] && [ -n "$DB_PASS" ]; then
    generate_env_file "$PROJECT" "$GEMINI_API_KEY" "$DB_PASS" "$ALLOYDB_CLUSTER" "$ALLOYDB_INSTANCE" "$ALLOYDB_REGION"
fi

echo ""

# ============================================================================
# Setup Application Default Credentials for Auth Proxy
# ============================================================================

echo "🔐 Checking authentication for AlloyDB Auth Proxy..."
echo ""

ADC_PATH="$HOME/.config/gcloud/application_default_credentials.json"

# Check if running on GCE/Cloud Shell
IS_GCE=0
if curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/id > /dev/null 2>&1; then
    IS_GCE=1
    echo "✅ Running on Google Cloud Shell / GCE"
    echo ""
    
    # Even on Cloud Shell, we need user credentials (not VM service account)
    # because the metadata service often has OAuth token issues
    if [ ! -f "$ADC_PATH" ]; then
        echo "⚠️  Application Default Credentials not found"
        echo ""
        echo "On Cloud Shell, the Auth Proxy needs YOUR user credentials"
        echo "(not the VM's service account) to avoid OAuth errors."
        echo ""
        echo "This is a one-time setup (~30 seconds)."
        echo ""
        read -p "Set up credentials now? (Y/n): " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            echo ""
            mkdir -p "$HOME/.config/gcloud"
            
            echo "Running: gcloud auth application-default login"
            echo ""
            echo "┌────────────────────────────────────────────────┐"
            echo "│  A browser link will be shown                 │"
            echo "│  1. Copy and open the link in your browser    │"
            echo "│  2. Sign in with your Google account          │"
            echo "│  3. Click 'Allow'                             │"
            echo "│  4. Copy the authorization code               │"
            echo "│  5. Paste it back here                        │"
            echo "└────────────────────────────────────────────────┘"
            echo ""
            
            gcloud auth application-default login --no-launch-browser
            
            # Check if it saved to /tmp (Cloud Shell issue)
            TEMP_ADC=$(find /tmp -name "application_default_credentials.json" 2>/dev/null | head -n 1)
            if [ -n "$TEMP_ADC" ] && [ -f "$TEMP_ADC" ]; then
                echo ""
                echo "📋 Moving credentials to standard location..."
                cp "$TEMP_ADC" "$ADC_PATH"
                chmod 600 "$ADC_PATH"
                echo "✅ Credentials saved to $ADC_PATH"
            elif [ -f "$ADC_PATH" ]; then
                echo ""
                echo "✅ Application Default Credentials configured"
            else
                echo ""
                echo "⚠️  Credentials setup completed, but file location unclear"
                echo "   Auth Proxy may have issues - re-run ./setup.sh if needed"
            fi
        else
            echo "⚠️  Skipping credential setup - Auth Proxy will likely fail"
            echo "   Re-run ./setup.sh later to fix authentication"
        fi
    else
        echo "✅ Application Default Credentials found"
    fi
else
    # Not on GCE - local machine
    if [ ! -f "$ADC_PATH" ]; then
        echo "⚠️  Application Default Credentials not found"
        echo ""
        echo "The Auth Proxy needs credentials to connect to AlloyDB."
        echo "This is a one-time setup that takes ~30 seconds."
        echo ""
        read -p "Set up credentials now? (Y/n): " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            echo ""
            echo "Running: gcloud auth application-default login"
            echo ""
            echo "┌────────────────────────────────────────────────┐"
            echo "│  A browser will open (or show a link)         │"
            echo "│  1. Sign in with your Google account          │"
            echo "│  2. Click 'Allow'                             │"
            echo "│  3. Copy the authorization code               │"
            echo "│  4. Paste it back here                        │"
            echo "└────────────────────────────────────────────────┘"
            echo ""
            
            gcloud auth application-default login
            
            if [ $? -eq 0 ]; then
                echo ""
                echo "✅ Application Default Credentials configured"
            else
                echo ""
                echo "❌ Failed to set up credentials"
                echo "   You can set up later with: gcloud auth application-default login"
                echo "   Continuing anyway..."
            fi
        else
            echo "⚠️  Skipping credential setup - Auth Proxy may fail"
        fi
    else
        echo "✅ Application Default Credentials found"
    fi
fi

echo ""

# Download and start Auth Proxy
echo "🔌 Starting AlloyDB Auth Proxy..."

# Detect OS and architecture
OS=$(detect_os)
ARCH=$(detect_arch)

PROXY_VERSION="v1.10.0"

case "$OS" in
    linux)
        if [ "$ARCH" = "arm64" ]; then
            PROXY_URL="https://storage.googleapis.com/alloydb-auth-proxy/${PROXY_VERSION}/alloydb-auth-proxy.linux.arm64"
        else
            PROXY_URL="https://storage.googleapis.com/alloydb-auth-proxy/${PROXY_VERSION}/alloydb-auth-proxy.linux.amd64"
        fi
        ;;
    darwin)
        if [ "$ARCH" = "arm64" ]; then
            PROXY_URL="https://storage.googleapis.com/alloydb-auth-proxy/${PROXY_VERSION}/alloydb-auth-proxy.darwin.arm64"
        else
            PROXY_URL="https://storage.googleapis.com/alloydb-auth-proxy/${PROXY_VERSION}/alloydb-auth-proxy.darwin.amd64"
        fi
        ;;
    *)
        echo "⚠️  Unknown OS: $OS, defaulting to Linux amd64"
        PROXY_URL="https://storage.googleapis.com/alloydb-auth-proxy/${PROXY_VERSION}/alloydb-auth-proxy.linux.amd64"
        ;;
esac

PROXY_BINARY="$SCRIPT_DIR/alloydb-auth-proxy"

# Download proxy if needed
if [ ! -f "$PROXY_BINARY" ]; then
    echo "📥 Downloading Auth Proxy ${PROXY_VERSION} for $OS/$ARCH..."
    if command -v wget &> /dev/null; then
        wget -q "$PROXY_URL" -O "$PROXY_BINARY" 2>&1
    else
        curl -s -o "$PROXY_BINARY" "$PROXY_URL"
    fi
    chmod +x "$PROXY_BINARY"
    echo "✅ Downloaded successfully"
else
    echo "✅ Auth Proxy binary already exists"
fi

echo "✅ Using instance: ${INSTANCE_URI}"

# Set explicit credentials path if ADC exists
if [ -f "$ADC_PATH" ]; then
    export GOOGLE_APPLICATION_CREDENTIALS="$ADC_PATH"
    echo "   Using credentials: $ADC_PATH"
fi

# ============================================================================
# Check and enable Public IP (required for Cloud Shell)
# ============================================================================
echo ""
echo "🌐 Checking AlloyDB Public IP status..."
PUBLIC_IP=$(gcloud alloydb instances describe "$ALLOYDB_INSTANCE" \
    --cluster="$ALLOYDB_CLUSTER" \
    --region="$ALLOYDB_REGION" \
    --format="value(publicIpAddress)" 2>/dev/null)

if [ -n "$PUBLIC_IP" ]; then
    echo "✅ Public IP already enabled: $PUBLIC_IP"
else
    echo "⚠️  Public IP is not enabled on this AlloyDB instance."
    echo ""
    # Cloud Shell cannot reach AlloyDB private IPs directly
    if [ -n "$CLOUD_SHELL" ] || [ -d /google ]; then
        echo "   Cloud Shell detected. Public IP is REQUIRED for connectivity."
    else
        echo "   If you're outside the AlloyDB VPC, Public IP is required."
    fi
    echo ""
    echo "   Security note: Public IP + Auth Proxy is secure because:"
    echo "   - All connections are mTLS encrypted via the Auth Proxy"
    echo "   - IAM authentication is required (no anonymous access)"
    echo "   - Password complexity is enforced (password.enforce_complexity=on)"
    echo ""
    read -p "   Enable Public IP now? (Y/n): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo "   ⚠️  Skipping Public IP enablement. Proxy may fail if not on the VPC."
    else
        echo "   Enabling Public IP (this takes ~2 minutes)..."
        if gcloud alloydb instances update "$ALLOYDB_INSTANCE" \
            --cluster="$ALLOYDB_CLUSTER" \
            --region="$ALLOYDB_REGION" \
            --assign-inbound-public-ip=ASSIGN_IPV4 \
            --database-flags=password.enforce_complexity=on \
            --quiet 2>&1; then
            echo "   ⏳ Waiting for Public IP to be assigned..."
            for i in {1..24}; do
                sleep 5
                PUBLIC_IP=$(gcloud alloydb instances describe "$ALLOYDB_INSTANCE" \
                    --cluster="$ALLOYDB_CLUSTER" \
                    --region="$ALLOYDB_REGION" \
                    --format="value(publicIpAddress)" 2>/dev/null)
                if [ -n "$PUBLIC_IP" ]; then
                    echo "   ✅ Public IP assigned: $PUBLIC_IP"
                    break
                fi
                echo -n "."
            done
            if [ -z "$PUBLIC_IP" ]; then
                echo ""
                echo "   ⚠️  Public IP not yet available. It may still be provisioning."
                echo "   Re-run setup.sh in a few minutes."
            fi
        else
            echo "   ❌ Failed to enable Public IP. You may need to do this manually:"
            echo "   gcloud alloydb instances update $ALLOYDB_INSTANCE \\"
            echo "     --cluster=$ALLOYDB_CLUSTER --region=$ALLOYDB_REGION \\"
            echo "     --assign-inbound-public-ip=ASSIGN_IPV4 \\"
            echo "     --database-flags=password.enforce_complexity=on"
        fi
    fi
fi

# Check if proxy is already running
EXISTING_PROXY_PID=$(pgrep -f "alloydb-auth-proxy" 2>/dev/null | head -n 1)
if [ -n "$EXISTING_PROXY_PID" ]; then
    echo "🔄 Existing Auth Proxy found (PID: $EXISTING_PROXY_PID)"
    echo "   Stopping old proxy to ensure clean restart..."
    kill $EXISTING_PROXY_PID 2>/dev/null || true
    sleep 2
fi

echo "🚀 Starting Auth Proxy with fresh credentials..."

# Ensure logs directory exists
mkdir -p "$SCRIPT_DIR/logs"

if [ -n "$PUBLIC_IP" ]; then
    echo "   ✅ Public IP detected: $PUBLIC_IP (using --public-ip flag)"
    nohup "$PROXY_BINARY" "$INSTANCE_URI" --public-ip > "$SCRIPT_DIR/logs/proxy.log" 2>&1 &
else
    echo "   Using private IP connection"
    nohup "$PROXY_BINARY" "$INSTANCE_URI" > "$SCRIPT_DIR/logs/proxy.log" 2>&1 &
fi

PROXY_PID=$!
echo "   PID: $PROXY_PID (logs: logs/proxy.log)"

# Wait for proxy to be ready - check for actual connection readiness
echo -n "   Waiting for proxy to initialize"
PROXY_READY=0
CONNECTION_ERRORS=0

for i in {1..30}; do
    echo -n "."
    sleep 1
    
    # Check if process died
    if ! kill -0 $PROXY_PID 2>/dev/null; then
        echo ""
        echo "❌ Auth Proxy process died. Check logs/proxy.log for details:"
        tail -20 "$SCRIPT_DIR/logs/proxy.log"
        echo ""
        echo "Common causes:"
        echo "  1. Missing Application Default Credentials"
        echo "     Fix: gcloud auth application-default login"
        echo "  2. Insufficient permissions on your account"
        echo "  3. AlloyDB API not enabled properly"
        exit 1
    fi
    
    # Check for OAuth errors in log
    if grep -q "oauth2.*invalid token" "$SCRIPT_DIR/logs/proxy.log" 2>/dev/null; then
        CONNECTION_ERRORS=1
    fi
    
    # Check if proxy is actually listening and ready (look for success message)
    if grep -q "ready for new connections" "$SCRIPT_DIR/logs/proxy.log" 2>/dev/null; then
        PROXY_READY=1
        # Give it 2 more seconds to fully stabilize
        sleep 2
        break
    fi
done
echo ""

if [ $CONNECTION_ERRORS -eq 1 ]; then
    echo "⚠️  Auth Proxy started but has OAuth authentication errors"
    echo ""
    echo "Quick fix: Run this command and follow the prompts:"
    echo "   gcloud auth application-default login --no-launch-browser"
    echo ""
    echo "Then restart:"
    echo "   kill $PROXY_PID"
    echo "   ./alloydb-auth-proxy $INSTANCE_URI > logs/proxy.log 2>&1 &"
    echo ""
    read -p "Try to continue anyway? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
elif [ $PROXY_READY -eq 1 ]; then
    echo "✅ Auth Proxy started successfully and ready for connections"
else
    echo "⚠️  Auth Proxy started but may need more time"
    echo "   Check logs/proxy.log if database connection fails"
fi

echo ""

# ============================================================================
# Step 5: Seed Database
# ============================================================================
echo "🌱 Step 5/5: Seeding database..."
echo ""

# Run seed script
echo "Creating schema and inserting sample data..."
cd "$SCRIPT_DIR/database"
python3 seed.py

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Database seeded successfully!"
else
    echo ""
    echo "❌ Database seeding failed"
    echo "   Check that DB_PASS is correct and Auth Proxy is running"
    exit 1
fi

cd "$SCRIPT_DIR"

# ============================================================================
# Setup Complete
# ============================================================================
echo ""
echo "╔════════════════════════════════════════════════╗"
echo "║  🎉 Setup Complete!                            ║"
echo "╠════════════════════════════════════════════════╣"
echo "║  Next steps:                                   ║"
echo "║  1. Run './run.sh' to start all services       ║"
echo "║  2. Open http://localhost:8080                 ║"
echo "║  3. Upload an image and watch the magic! ✨    ║"
echo "║                                                ║"
echo "║  Sample images available in test-images/       ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
if [ -f "$SCRIPT_DIR/.env" ]; then
    echo "💾 Configuration saved to .env file"
    echo "   Future runs will automatically load these settings"
else
    echo "⚠️  .env file not created (missing credentials)"
    echo ""
    echo "To create .env manually, set these environment variables:"
    echo "  export GEMINI_API_KEY='your-api-key'"
    echo "  export GOOGLE_CLOUD_PROJECT=$PROJECT"
    echo "  export DB_PASS='your-password'"
fi
echo ""
